name: Workflow Cleanup

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 3 * * *' 

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write 
      contents: read

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 2 
          keep_minimum_runs: 5 
