name: Preisüberwachung

on:
  workflow_dispatch: # Manuelles Starten ermöglichen
  schedule:
    - cron: '0 * * * *' # Läuft jede Stunde

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen (Checkout ins richtige Verzeichnis)
        uses: actions/checkout@v3
        with:
          path: pricecheck

      - name: Debugging - Zeige Dateien in GitHub Actions
        run: ls -R
        working-directory: pricecheck

      - name: Node.js installieren
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Abhängigkeiten installieren
        run: npm install
        working-directory: pricecheck

      - name: Skript ausführen
        env:
          URL: ${{ secrets.URL }}
          EXPECTED_PRICE_PREFIX: ${{ secrets.EXPECTED_PRICE_PREFIX }}
          WHATSAPP_API_URL: ${{ secrets.WHATSAPP_API_URL }}
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
          API_KEY: ${{ secrets.API_KEY }}
        run: node priceCheck.js
        working-directory: pricecheck
